language: generic
sudo: required


# run docker
services:
  - docker

# build image using Dockerfile.dev
before_install:
  - docker build -t milofryling/docker-react -f Dockerfile.dev .

#Tell Travis how to run our test suite
script:
  - docker run -e CI=true milofryling/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-807111812405"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
      secure: "$AWS_ACCESS_KEY"
  secret_access_key:
      secure: "$AWS_SECRET_KEY"